
var ChemicalNames = "";
var categoryvalues = "";
var Areaofapplicationvalues = ""; 
var StatusValues = "";
var FileTypeValues = "";
var doc2 = "";
var rowNum1 = 1;
var rowNum2 = 1;

$(document).ready(function () {
    
    $.get("/api/ApprovedChemicalList/Load")
        .done(function (result) {

            var loadResult = JSON.parse(result);
           
            categoryvalues = "<option value=''>" + "Select" + "</option>";
            Areaofapplicationvalues = "<option value=''>" + "Select" + "</option>"; 
            ChemicalNames = "<option value=''>" + "Select" + "</option>";
            FileTypeValues = "<option value=''>" + "Select" + "</option>";

            for (var i = 0; i < loadResult.CategoryLovs1.length; i++) {
                categoryvalues += "<option value=" + loadResult.CategoryLovs1[i].LovId + ">" + loadResult.CategoryLovs1[i].FieldValue + "</option>"
            }
            $("#tblCategory tbody #ddlCategory1").append(categoryvalues);

            for (var i = 0; i < loadResult.AreaOfApplicationLovs.length; i++) {
                Areaofapplicationvalues += "<option value=" + loadResult.AreaOfApplicationLovs[i].LovId + ">" + loadResult.AreaOfApplicationLovs[i].FieldValue + "</option>"
            }
            $("#tblCategory tbody #ddlAreaofApplication1").append(Areaofapplicationvalues);


            for (var i = 0; i < loadResult.StatusLovs.length; i++) {              
                    StatusValues+= "<option value=" + loadResult.StatusLovs[i].LovId + ">" + loadResult.StatusLovs[i].FieldValue + "</option>"               
            }  
            $("#tblCategory tbody #ddlStatus1").append(StatusValues);
                        

            for (var i = 0; i < loadResult.ChemicalNames.length; i++) {
                ChemicalNames += "<option value=" + loadResult.ChemicalNames[i].LovId + ">" + loadResult.ChemicalNames[i].FieldValue + "</option>"
            }
            $("#tblCategory tbody #ddlChemicalName1").append(ChemicalNames);

            for (var i = 0; i < loadResult.FileTypeLovs.length; i++) {
                FileTypeValues += "<option value=" + loadResult.FileTypeLovs[i].LovId + ">" + loadResult.FileTypeLovs[i].FieldValue + "</option>"
            }
            $("#tblAttachment tbody #ddlFileType1").append(FileTypeValues);

            
            
            $('#myPleaseWait').modal('hide');
        })
        .fail(function (response) {
            $('#myPleaseWait').modal('hide');
            $("div.errormsgcenter").text(Messages.COMMON_FAILURE_MESSAGE(response));
            $('#errorMsgConfigAdditionalFields').css('visibility', 'visible');
        });
    

    autoGeneratedCode();

    
    $("#btnSave, #btnSaveandAddNew").click(function () {
        
        $("div.errormsgcenter").text("");
        var CurrentbtnID = $(this).attr("Id");
        $('#errorMsg').css('visibility', 'hidden');

        var isFormValid = formInputValidation("formChemicalInUse", 'save');

        if (!isFormValid) {
            $("div.errormsgcenter").text(Messages.INVALID_INPUT_MESSAGE);
            $('#errorMsg').css('visibility', 'visible');
            return false;
        }

        var primaryId = 0;
        if ($("#primaryID").val() != null) {
            primaryId = $("#primaryID").val();           
        }        

        var obj = {
            CustomerId: $('#selCustomerLayout').val(),
            FacilityId: $('#selFacilityLayout').val(),
            ChemicalId: primaryId,
            DocumentNo: $('#txtDocumentNo').val(),
            Date: $('#txtDate').val(),
            Remarks: $('#txtRemarks').val(),
            ChemicalsList: []
        }

        $('#tblCategory tbody tr').each(function () {
            var tbl = {};
            tbl.CategoryId = $(this).find("[id^=hdnCategoryId]")[0].value; 
            tbl.ChemicalInUseId = primaryId; 
            tbl.Category = $(this).find("[id^=ddlCategory]")[0].value;
            tbl.AreaofApplication = $(this).find("[id^=ddlAreaofApplication]")[0].value;
            tbl.ChemicalId = $(this).find("[id^=ddlChemicalName]")[0].value; 
            tbl.KMMNO = $(this).find("[id^=txtKMMNO]")[0].value;
            tbl.Properties = $(this).find("[id^=txtProperties]")[0].value;
            tbl.Status = $(this).find("[id^=ddlStatus]")[0].value;
            tbl.EffectiveDate = $(this).find("[id^=txtEffectiveDate]")[0].value;
            tbl.isDeleted = $(this).find('input:checkbox[id^=isDelete]').prop("checked");
            
            obj.ChemicalsList.push(tbl);
        });
       
        $.post("/api/ChemicalInUse/Save", obj, function (response) {

            var result = JSON.parse(response);
            showMessage('ChemicalInUse', CURD_MESSAGE_STATUS.SS);

                      
           // $("#primaryID").val(result.ChemicalId);
            $("#grid").trigger('reloadGrid');          
            
            if (CurrentbtnID == "btnSaveandAddNew") {
                EmptyFields();
            }
            else {
                fillDetails(result);
            }
        },
            "json")
            .fail(function (response) {

                var errorMessage = "";
                if (response.status == 400) {
                    errorMessage = response.responseJSON;
                }
                else {
                    errorMessage = Messages.COMMON_FAILURE_MESSAGE(response);
                }
                $("div.errormsgcenter").text(errorMessage);
                $('#errorMsg').css('visibility', 'visible');

                $('#btnSave').attr('disabled', false);

            });
        
               

    });

    //Reset Button Functionality...
    $("#btnCancel").click(function () {

        bootbox.confirm({
            message: Messages.Reset_Alert_CONFIRMATION,
            buttons: {
                confirm: {
                    label: 'Yes',
                    className: 'btn-primary'
                },
                cancel: {
                    label: 'No',
                    className: 'btn-default'
                }
            },
            callback: function (result) {
                if (result) {
                    EmptyFields();
                }
                else {
                    $('#myPleaseWait').modal('hide');
                }
                //console.log('This was logged in the callback: ' + result);
            }
        });

        
    });

    //ChemicalInUse Attachment Tab........
    $("#btnSaveAttachment").click(function () {

        $("div.errormsgcenter").text("");
        var CurrentbtnID = $(this).attr("Id");
        $('#errorMsg1').css('visibility', 'hidden');

        var primaryId = 0;
        if ($("#primaryID").val() != null) {
            primaryId = $("#primaryID").val();
        }

        var isFormValid = formInputValidation("formAttachments", 'save');
        if (!isFormValid) {
            $("div.errormsgcenter").text(Messages.INVALID_INPUT_MESSAGE);
            $('#errorMsg1').css('visibility', 'visible');
            return false;
        }

        var isValidAttachments = true;
        $('#tbodyAttachments tr').each(function () {
            if ($(this).find("[id^=icon]")[0] == undefined) {
                isValidAttachments = false;
                return;
            }
        });

        if (isValidAttachments == false) {
            $("div.errormsgcenter").text(' Please select the file to proceed. ');
            $('#errorMsg1').css('visibility', 'visible');
            return false;
        }

        var obj = {
            ChemicalId: primaryId,
            lstChemicalInUseAttachments: []
        }
               
        $('#tbodyAttachments tr').each(function () {

            var tbl = {};
            tbl.AttachmentId = $(this).find("[id^=hdnAttachmentId]")[0].value;
            tbl.FileType = $(this).find("[id^=ddlFileType]")[0].value;
            tbl.FileName = $(this).find("[id^=txtFileName]")[0].value;
            if ($(this).find("[id^=txtAttachment]")[0].files.length != 0) {
                tbl.AttachmentName = $(this).find("[id^=txtAttachment]")[0].files[0].name;
            }
            tbl.FilePath = $(this).find("[id^=icon]")[0].pathname;
            tbl.isDeleted = $(this).find('input:checkbox[id^=isDelete]').prop("checked");

            
            obj.lstChemicalInUseAttachments.push(tbl);
        });



        $.post("/api/ChemicalInUse/AttachmentSave", obj, function (response) {

            var result = JSON.parse(response);
            showMessage('ChemicalInUse Attachment', CURD_MESSAGE_STATUS.SS);

            if (result != null) {
                fillAttachment(result);
            }

        },
            "json")
            .fail(function (response) {

                var errorMessage = "";
                if (response.status == 400) {
                    errorMessage = response.responseJSON;
                }
                else {
                    errorMessage = Messages.COMMON_FAILURE_MESSAGE(response);
                }
                $("div.errormsgcenter").text(errorMessage);
                $('#errorMsg1').css('visibility', 'hidden');

                $('#btnSaveAttachment').attr('disabled', false);

            });
    
       
       

    });
        
    $("#addCategoryRow").click(function () {    

        rowNum1 += 1;

        addCategoryRow(rowNum1);    
        
    });

   

    //Attachment Add Rows Code.....
   
    $("#addAttachmentRow").click(function () {

        rowNum2 = rowNum2 + 1;

        addAttachmentRow(rowNum2);  
        
    });
    
  
    //****************************************** Mutliple rows delete button code******************************************
    $("#deleteCategoryRows").click(function () {
        bootbox.confirm({
            message: 'Do you want to delete a row?',
            buttons: {
                confirm: {
                    label: 'Yes',
                    className: 'btn-primary'
                },
                cancel: {
                    label: 'No',
                    className: 'btn-default'
                }
            },
            callback: function (result) {
                if (result) {
                    if ($("input[type='checkbox']:checked").length > 0) {
                        $("#tbodyCategory tr").find('input[name="isDelete"]').each(function () {
                            if ($(this).is(":checked")) {
                                if ($(this).closest("tr").find("[id^=hdnCategoryId]").val() == 0) {
                                    $(this).closest("tr").remove();
                                }
                            }
                        });
                    }
                    else
                        bootbox.alert("Please select atleast one row !");
                }
                else {
                    $('#myPleaseWait').modal('hide');
                }
            }
        });
    });

    $("#deleteAttachmentRows").click(function () {
        bootbox.confirm({
            message: 'Do you want to delete a row?',
            buttons: {
                confirm: {
                    label: 'Yes',
                    className: 'btn-primary'
                },
                cancel: {
                    label: 'No',
                    className: 'btn-default'
                }
            },
            callback: function (result) {
                if (result) {
                    if ($("input[type='checkbox']:checked").length > 0) {
                        $("#tbodyAttachments tr").find('input[name="isDelete"]').each(function () {
                            if ($(this).is(":checked")) {
                                if ($(this).closest("tr").find("[id^=hdnAttachmentId]").val() == 0) {
                                    $(this).closest("tr").remove();
                                }
                            }
                        });
                    }
                    else
                        bootbox.alert("Please select atleast one row !");
                }
                else {
                    $('#myPleaseWait').modal('hide');
                }
            }
        });
    });

    
         
    $('body').on('change', '.ChemicalName', function (e) {
            var controlId = event.target.id;
            
        var ChemicalId = $('#' + controlId).val();
                
        var jqxhr = $.get("/api/ChemicalInUse/ChemicalNameData/" + ChemicalId, function (response) {
            var result = JSON.parse(response);

            var kkmno = result.KMMNO;
            var properties = result.Properties;
            var status = result.Status;
            var effective = getCustomDate(result.EffectiveDate);

            var id = controlId.slice(15, 17);
            $('#txtKMMNO' + id).val(kkmno);
            $('#txtProperties' + id).val(properties);
            $('#ddlStatus' + id).val(status);
            $('#txtEffectiveDate' + id).val(effective);

        })                      
    });
       
    var getUrlParameter = function getUrlParameter(sParam) {
        var sPageURL = decodeURIComponent(window.location.search.substring(1)),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] === sParam) {
                return sParameterName[1] === undefined ? true : sParameterName[1];
            }
        }
    };
    var ID = getUrlParameter('id');
    if (ID == null || ID == undefined || ID == 0 || ID == '' || ID == "") {
        $("#jQGridCollapse1").click();
    }
    else {
        LinkClicked(ID);
    }
    
    $('#txtDate').change('change', function () {
        $('#datetable').removeClass('has-error');
    });

    $('#ddlCategory').on('change', function () {
        $('#formChemicalInUse #myTd').removeClass('has-error');
    });

    $('#ddlAreaofApplication').change(function () {
        $('#formChemicalInUse #td1').removeClass('has-error');
    });

    $('#ddlChemicalName').change(function () {

        $('#formChemicalInUse #td2').removeClass('has-error');
        $('#errorMsg').css('visibility', 'hidden');
    });

    $("[id^=ddlFileType]").change(function () {
        $(this).parent.removeClass('has-error');
    });

    $('[id^=txtFileName]').keypress(function () {
        $('#formchemical #fname').removeClass('has-error');
        $('#errorMsg1').css('visibility', 'hidden');
    });
      
    $('body').on('change', '.fileAttachment', function (e) {
                
        var AttachIdId = event.target.id;
        var id = AttachIdId.slice(13, 15);
        var fileUpload = $(this).get(0);
        var files = fileUpload.files;

        var fileData = new FormData();

        var d = new Date();
        var day = d.getDate();
        var month = d.getMonth() + 1;
        var year = d.getFullYear();
        if (day < 10) {
            day = "0" + day;
        }
        if (month < 10) {
            month = "0" + month;
        }
        var fileName = "CIU_" + year + month + day + "_" + Math.floor(Math.random() * 100000);

        fileData.append(fileName, files[0]);

        $.ajax({
            url: '/api/Common/FileUpload',
            type: "POST",
            contentType: false, // Not to set any content header  
            processData: false, // Not to process data  
            data: fileData,
            success: function (result) {               

                if (result == "File Uploaded Successfully!") {


                    $('#icon' + id).remove();
                    if (id >= 1) {
                        $('#cell' + id).append(
                            '<a href="" style="color:cornflowerblue" download="" id="icon' + id + '"><span style="text-align:center"><i class="fa fa-download" style="font-size:15px;"></i></span> </a>'
                        );
                    }
                    else {
                        $('#cell').append(
                            '<a href="" style="color:cornflowerblue" download="" id="icon"><span style="text-align:center"><i class="fa fa-download" style="font-size:15px;"></i></span> </a>'
                        );
                    }

                    var testFileName = $('#txtAttachment' + id).val();
                    // Get the extension from the filename
                    var extn = testFileName.split('.').pop();

                    $("#icon" + id).attr("href", "../uploads/attachments/" + fileName + "." + extn);
                }
            },
            error: function (err) {

                var errorMessage = "";
                if (err.status == 400) {
                    errorMessage = response.responseJSON;
                }
                else {
                    errorMessage = Messages.COMMON_FAILURE_MESSAGE(err);
                }
                $("div.errormsgcenter").text(errorMessage);
                $('#errorMsg').css('visibility', 'visible');
                $('#btnSave').attr('disabled', false);
            }  
        });
    });

   
    $(".nav-tabs > li:not(:first-child)").click(function () {
        var primaryId = $('#primaryID').val();
        if (primaryId == 0) {
            bootbox.alert("Save the details before moving on to Other!");
            return false;
        }
    });

});

$("#jQGridCollapse1").click(function () {
    // $(".jqContainer").toggleClass("hide_container");
    var pro = new Promise(function (res, err) {
        $(".jqContainer").toggleClass("hide_container");
        res(1);
    })
    pro.then(
        function resposes() {
            setTimeout(() => $(".content").scrollTop(3000), 1);
        })
})

function LinkClicked(id) {

    $(".content").scrollTop(1);
    $('.nav-tabs a:first').tab('show');
    $("#formBemsBlock :input:not(:button)").parent().removeClass('has-error');
    $("div.errormsgcenter").text("");
    $('#errorMsg').css('visibility', 'hidden');
    var action = "";
    $('#primaryID').val(id);
    var hasEditPermission = Enumerable.From(JSON.parse($('#ActionPermissionValues').val())).Any("$.ActionPermissionName=='Edit'");
    var hasViewPermission = Enumerable.From(JSON.parse($('#ActionPermissionValues').val())).Any("$.ActionPermissionName=='View'");
    var hasDeletePermission = Enumerable.From(JSON.parse($('#ActionPermissionValues').val())).Any("$.ActionPermissionName=='Delete'");

    if (hasEditPermission) {
        action = "Edit"
    }
    else if (!hasEditPermission && hasViewPermission) {
        action = "View"
    }
    if (action == "Edit" && hasDeletePermission) {
        $('#btnDelete').show();
    }

    if (action == 'View') {
        $("#formBemsBlock :input:not(:button)").prop("disabled", true);
    } else {
        $('#btnEdit').show();
       
        $('#btnNextScreenSave').show();
    }
    $('#spnActionType').text(action);

    var primaryId = $('#primaryID').val();

    if (primaryId != null && primaryId != "0") {
        $.get("/api/ChemicalInUse/Get/" + primaryId)
            .done(function (result) {
                var getResult = JSON.parse(result);
                fillDetails(getResult);                               
            })
            .fail(function () {
                $('#myPleaseWait').modal('hide');
                $("div.errormsgcenter").text(Messages.COMMON_FAILURE_MESSAGE);
                $('#errorMsg').css('visibility', 'visible');
            });
    }
    else {
        $('#myPleaseWait').modal('hide');
    }
}

function fillDetails(result) {

    if (result != undefined) {

        var Docno = result.DocumentNo;
        var varDate = getCustomDate(result.Date);
        var remark = result.Remarks;

        $("#primaryID").val(result.ChemicalId);
        $('#txtDocumentNo').val(Docno);      
        $('#txtDate').val(varDate);
        $('#txtRemarks').val(remark);
    }
         
    rowNum1 = 1;
    $("#tbodyCategory").html('');

    if (result.ChemicalsList != null) {
        $('#table_data1').hide();
        
        for (var i = 0; i < result.ChemicalsList.length; i++) {
            
            addCategoryRow(rowNum1);   
            
            $('#hdnCategoryId' + rowNum1).val(result.ChemicalsList[i].CategoryId);
            $('#ddlCategory' + rowNum1).val(result.ChemicalsList[i].Category);
            $('#ddlAreaofApplication' + rowNum1).val(result.ChemicalsList[i].AreaofApplication);
            $('#ddlChemicalName' + rowNum1).val(result.ChemicalsList[i].ChemicalId);
            $('#txtKMMNO' + rowNum1).val(result.ChemicalsList[i].KMMNO);
            $('#txtProperties' + rowNum1).val(result.ChemicalsList[i].Properties);
            $('#ddlStatus' + rowNum1).val(result.ChemicalsList[i].Status);
            var effedate = getCustomDate(result.ChemicalsList[i].EffectiveDate);

            $('#txtEffectiveDate' + rowNum1).val(effedate);

            rowNum1 += 1;
        }
    }
    else {
        addCategoryRow(rowNum1);       
    }

    fillAttachment(result.AttachmentList);
  

}

function fillAttachment(result) {

    $('#tbodyAttachments').html('');
    rowNum2 = 1;

    if (result != null) {

        $('#table_data').hide();
        
        for (var k = 0; k < result.length; k++) {

            addAttachmentRow(rowNum2);
                      
            $('#hdnAttachmentId' + rowNum2).val(result[k].AttachmentId);
            $('#ddlFileType' + rowNum2).val(result[k].FileType);
            $('#txtFileName' + rowNum2).val(result[k].FileName);
            //$('#txtAttachment' + rowNum2)[0].files.append(file);            

            var FilePath = result[k].FilePath
            $('#cell' + rowNum2).append(
                '<a href="' + FilePath + '" style="color:cornflowerblue" download="" id="icon' + rowNum2 + '"><span style="text-align:center"><i class="fa fa-download" style="font-size:15px;"></i></span> </a>'
            );

            rowNum2 += 1;
        }
    }
    else {
        addAttachmentRow(1);
    }

}

function addCategoryRow(num) {

    var CheckBox = '<td style="text-align:center"><input type="checkbox" id="isDeleted' + num + '" name="isDelete" /><input type="hidden" value="0" id="hdnCategoryId' + num + '"  /></td>';

    var Category = '<td id="myTd"><select type="text" required class="form-control" id="ddlCategory' + num + '" autocomplete="off" name="Category" maxlength="25" >' + categoryvalues + ' </select ></td>';

    var AreaofApplication = '<td id="td1"> <select type="text" required class="form-control" id="ddlAreaofApplication' + num + '" autocomplete="off" name="AreaofApplication" maxlength="25" >' + Areaofapplicationvalues + ' </select ></td>';

    var ChemicalName = '<td id="td2"> <select type="text" required class="form-control ChemicalName" id="ddlChemicalName' + num + '" autocomplete="off" name="ChemicalName" maxlength="25" >' + ChemicalNames + '</select> </td>';

    var KMMNO = '<td><input type="text" class="form-control" id="txtKMMNO' + num + '"   disabled="disabled"  autocomplete="off"   name="KMMNO" maxlength="25"  /></td>';

    var Properties = '<td><input type="text" class="form-control" id="txtProperties' + num + '"  disabled="disabled" autocomplete="off"  name="Properties" maxlength="25"  /></td>';

    var Status = '<td> <select type="text" class="form-control" id="ddlStatus' + num + '" autocomplete="off" disabled="disabled" name="Status" maxlength="25" > ' + StatusValues + '  </select ></td>';

    var EffectiveDate = '<td><input type="text" class="form-control" id="txtEffectiveDate' + num + '"   disabled="disabled" autocomplete="off"  name="EffectiveDate" maxlength="25"  /></td>';

    $("#tbodyCategory").append('<tr class="tablerow">' + CheckBox + Category + AreaofApplication + ChemicalName + KMMNO + Properties + Status + EffectiveDate + '</tr>');
       

    $('#table_data1').hide();

}

function addAttachmentRow(num) {

    var CheckBox = '<td style="text-align:center"><input type="checkbox" id="isDelete' + num + '" name="isDelete" /><input type="hidden" id="hdnAttachmentId' + num + '" value="0" /></td>';
    var FileType = '<td id="filetypee"> <select type="text" required class="form-control" id="ddlFileType' + num + '" autocomplete="off" name="FileType" maxlength="25" > ' + FileTypeValues + ' </select>  </td>';
    var FileName = '<td id="fname"><input type="text" required class="form-control" id="txtFileName' + num + '" autocomplete="off" name="FileName" maxlength="25"  /></td>';
    var Attachment = '<td id="attachment"> <input type="file" id="txtAttachment' + num + '" name="fileAttachment" required class="form-control fileAttachment" /></td>';
    var Download = '<td style="text-align:center" id="cell' + num + '">  </td>';

    $("#tblAttachment tbody").append('<tr>' + CheckBox + FileType + FileName + Attachment + Download + '</tr>');

   

    $('#table_data').hide();

}

function EmptyFields() {

    autoGeneratedCode();    

    $('#formChemicalInUse')[0].reset();

    $('#primaryID').val(0);
    $('[id^=hdnCategoryId]').val(0);
    $('[id^=hdnAttachmentId]').val(0);

    $('#formChemicalInUse #txtDate').val('');
    $('#formChemicalInUse #txtRemarks').val(''); 
    $('#datetable').removeClass('has-error');
    $('#formChemicalInUse #myTd').removeClass('has-error');
    $('#formChemicalInUse #td1').removeClass('has-error');
    $('#formChemicalInUse #td2').removeClass('has-error');
    $('#errorMsg').css('visibility', 'hidden');

    rowNum1 = 1;
    rowNum2 = 1;
    var i = 1;
    $("#tbodyCategory").find('tr').each(function () {
        if (i > 1) {
            $(this).remove();
        }
        i += 1;
    });

    i = 1;
    $("#tbodyAttachments").find('tr').each(function () {
        if (i > 1) {
            $(this).remove();
        }
        i += 1;
    });


}

function autoGeneratedCode() {

    var DocumentNo = $('#txtDocumentNo').val();
    var obj1 = {
        DocumentNo: DocumentNo
    }

    $.get("/api/ChemicalInUse/AutoGeneratedCode", obj1, function (response) {

        var result = JSON.parse(response);
        var DocmentNo = result.DocumentNo;       
        $('#txtDocumentNo').val(DocmentNo);
    });

}


function getCustomDate(date) {

    if (date == '' || date == null) {
        return '';
    }
    else {
        let monthNames = ["Zero", "Jan", "Feb", "Mar", "Apr",
            "May", "Jun", "Jul", "Aug",
            "Sep", "Oct", "Nov", "Dec"];

        var day = date.slice(8, 10);
        var monthindex = date.slice(5, 7);        if (monthindex >= 10) {            var month = monthNames[date.slice(5, 7)];        }        else {            var month = monthNames[date.slice(6, 7)];        }
        var year = date.slice(0, 4);

        return day + "-" + month + "-" + year;
    }
}




