using CP.UETrack.Model;
using CP.UETrack.Model.HWMS;
using System.Collections.Generic;

namespace CP.UETrack.DAL.DataAccess.Contracts.HWMS
{
    public interface ICorrectiveActionReportsDAL
    {
        CorrectiveActionReports Save(CorrectiveActionReports block, out string ErrorMessage);
        CorrectiveActionReports AutoGeneratedCode();
        CorrectiveActionReports Get(int Id);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        List<CARAttachment> AttachmentSave(CorrectiveActionReports block, out string ErrorMessage);
        List<CorrectiveActionReports> FollowUpCARNoFetch(CorrectiveActionReports SearchObject);
    }
}
