using CP.UETrack.Model;
using CP.UETrack.Model.HWMS;
using System.Collections.Generic;

namespace CP.UETrack.DAL.DataAccess.Contracts.HWMS
{
  public  interface ICSWRecordSheetDAL
    {
        CSWRecordSheetDropdown Load();
        CSWRecordSheet Save(CSWRecordSheet block, out string ErrorMessage);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        CSWRecordSheet Get(int Id);
        CSWRecordSheet AutoGeneratedCode();
        List<CSWRecordSheet> AutoDisplaying();
        CSWRecordSheet WasteCodeGet(string WasteType);
  }
}
