using CP.UETrack.Model;
using CP.UETrack.Model.HWMS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CP.UETrack.DAL.DataAccess.Contracts.HWMS
{
   public interface IDailyWeighingRecordDAL
    {
        DailyWeighingRecordDropDown Load();
        List<BinMasterTable> BinNoCodeFetch(BinMasterTable SearchObject);
        DailyWeighingRecord Save(DailyWeighingRecord block, out string ErrorMessage);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        DailyWeighingRecord AutoGeneratedCode();
        DailyWeighingRecord Get(int Id);
    }
}
