//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UETrack.Application.Web
{
    using CP.Framework.Common.Logging;
    using CP.UETrack.Application.Web.API;
    using CP.UETrack.Application.Web.Filter;
    using CP.UETrack.Model.Common;
    using Helpers;
    using System.Net.Http;
    using System.Reflection;
    using System.Threading.Tasks;
    using System.Web.Http;

    [RoutePrefix("api/Common")]
    [WebApiAuthentication]
    public class CommonAPIController : BaseApiController
    {

        [System.Web.Http.HttpPostAttribute("exportdetails")]
        public Task<HttpResponseMessage> ExportDetails(System.Net.Http.Formatting.FormDataCollection form)
        {
            var result = RestHelper.ApiPost("common/exportdetails", form);
            return result;
        }

        [System.Web.Http.HttpPostAttribute("export")]
        public Task<HttpResponseMessage> Export(System.Net.Http.Formatting.FormDataCollection form)
        {
            var result = RestHelper.ApiPost("common1/export", form);
            return result;
        }


        [System.Web.Http.HttpGetAttribute("Download/{Id}")]
        public Task<HttpResponseMessage> Download(string Id)
        {
            Log4NetLogger.LogEntry(GetType().Name, MethodBase.GetCurrentMethod().Name, Level.Info.ToString());
            var result = RestHelper.ApiGet(string.Format("Common1/Download/{0}", Id));
            Log4NetLogger.LogExit(GetType().Name, MethodBase.GetCurrentMethod().Name, Level.Info.ToString());
            return result;
        }
        [System.Web.Http.HttpPostAttribute("GetHelpDescription")]
        public Task<HttpResponseMessage> GetHelpDescription(Helpdescription form)
        {
            Log4NetLogger.LogEntry(GetType().Name, MethodBase.GetCurrentMethod().Name, Level.Info.ToString());
            var result = RestHelper.ApiPost("Common1/GetHelpDescription", form);
            Log4NetLogger.LogExit(GetType().Name, MethodBase.GetCurrentMethod().Name, Level.Info.ToString());
            return result;
        }

        [System.Web.Http.HttpGetAttribute("History/{GuId}/{PageIndex}/{PageSize}")]
        public Task<HttpResponseMessage> History(string GuId, int PageIndex, int PageSize)
        {
            Log4NetLogger.LogEntry(GetType().Name, MethodBase.GetCurrentMethod().Name, Level.Info.ToString());
            var result = RestHelper.ApiGet(string.Format("Common1/History/{0}/{1}/{2}", GuId, PageIndex, PageSize));
            Log4NetLogger.LogExit(GetType().Name, MethodBase.GetCurrentMethod().Name, Level.Info.ToString());
            return result;
        }
    }
   
}
