//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.Framework.Common.ScheduledJobs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledJob
    {
        public int ScheduledJobId { get; set; }
        public string JobName { get; set; }
        public string FrequencyCode { get; set; }
        public int EveryXMinutes { get; set; }
        public string WeekDays { get; set; }
        public string MonthDates { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public System.TimeSpan JobTime { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.DateTime> LastRunOn { get; set; }
        public int LastRunStatusCode { get; set; }
        public string LastRunMessage { get; set; }
        public bool SendEmailOnSuccess { get; set; }
        public bool SendEmailOnFailure { get; set; }
        public string ToEmailIds { get; set; }
        public string CcEmailIds { get; set; }
    }
}
