using CP.UETrack.Model.CLS;
using CP.UETrack.Model;
using System.Collections.Generic;

namespace CP.UETrack.BLL.BusinessAccess.Contracts.CLS
{
   public interface IChemicalInUseBAL
    {
        ChemicalInUse Save(ChemicalInUse userRole, out string ErrorMessage);
        List<ChemicalInUseAttachments> AttachmentSave(ChemicalInUse userRole, out string ErrorMessage);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        ChemicalInUse Get(int Id);
        void Delete(int Id, out string ErrorMessage);
        void CategoryRowsDelete(int ID, out string ErrorMessage);
        ChemicalInUse AutoGeneratedCode();
        Chemicals ChemicalNameData(int ChemicalId);
    }
}
