using CP.UETrack.Model;
using CP.UETrack.Model.CLS;

namespace CP.UETrack.BLL.BusinessAccess.Contracts.CLS
{
   public interface IDailyCleaningActivityBAL
    {
        DailyCleaningActivityDropDown Load();
        DailyCleaningActivity Save(DailyCleaningActivity block, out string ErrorMessage);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        DailyCleaningActivity Get(int Id);
        DailyCleaningActivity AutoGeneratedCode();
        DailyCleaningActivity DocFetch(DailyCleaningActivity dailyCleaning);
    }
}
