using CP.UETrack.Model;
using CP.UETrack.Model.CLS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CP.UETrack.CLS.BusinessAccess.Interface
{
    public interface IPeriodicWorkRecordBAL
    {
        PeriodidcWorkRecordDropdown Load();
        PeriodicWorkRecord Save(PeriodicWorkRecord userRole, out string ErrorMessage);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        PeriodicWorkRecord Get(int Id);
        PeriodicWorkRecord AutoGeneratedCode();
        PeriodicWorkRecord DocFetch(PeriodicWorkRecord periodicWork);
    } 
}
