using CP.UETrack.Model.HWMS;
using CP.UETrack.Model;
using System.Collections.Generic;

namespace CP.UETrack.BLL.BusinessAccess.Contracts.HWMS
{
    public interface ICorrectiveActionReportsBAL
    {
        CorrectiveActionReports Save(CorrectiveActionReports userRole, out string ErrorMessage);
        CorrectiveActionReports AutoGeneratedCode();
        CorrectiveActionReports Get(int Id);
       
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        List<CARAttachment> AttachmentSave(CorrectiveActionReports userRole, out string ErrorMessage);
        List<CorrectiveActionReports> FollowUpCARNoFetch(CorrectiveActionReports SearchObject);
    }
}
