using CP.UETrack.Model;
using CP.UETrack.Model.HWMS;
using System.Collections.Generic;

namespace CP.UETrack.BLL.BusinessAccess.Contracts.HWMS
{
  public  interface ICSWRecordSheetBAL
    {
        CSWRecordSheet Save(CSWRecordSheet userRole, out string ErrorMessage);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        CSWRecordSheet Get(int Id);
        CSWRecordSheetDropdown Load();
        CSWRecordSheet AutoGeneratedCode();
        List<CSWRecordSheet> AutoDisplaying();
        CSWRecordSheet WasteCodeGet(string WasteType);
    }
}
