using CP.UETrack.Model;
using CP.UETrack.Model.HWMS;
using System.Collections.Generic;

namespace CP.UETrack.BLL.BusinessAccess.Contracts.HWMS
{
    public interface IOSWRecordSheetBAL
    {
        OSWRecordSheetDropDown Load();
        OSWRecordSheet AutoGeneratedCode();
        OSWRecordSheet Save(OSWRecordSheet userRole, out string ErrorMessage);
        List<OSWRecordSheet> UserAreaCodeFetch(OSWRecordSheet SearchObject);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        OSWRecordSheet Get(int Id);
    }
}
