//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.UETrack.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UETrackSysLovMst
    {
        public int LovId { get; set; }
        public string ModuleName { get; set; }
        public string ScreenName { get; set; }
        public string FieldName { get; set; }
        public string LovKey { get; set; }
        public string FieldCode { get; set; }
        public string FieldValue { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int SortNo { get; set; }
        public bool IsDefault { get; set; }
        public bool IsEditable { get; set; }
    }
}
