using CP.UETrack.Model;
using CP.UETrack.Model.CLS;
using System.Collections.Generic;

namespace CP.UETrack.DAL.DataAccess.Contracts.CLS
{
   public interface IChemicalInUseDAL
    {
        ChemicalInUse Save(ChemicalInUse block, out string ErrorMessage);
        List<ChemicalInUseAttachments> AttachmentSave(ChemicalInUse block, out string ErrorMessage);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        ChemicalInUse Get(int Id);
        void Delete(int Id, out string ErrorMessage);
        void CategoryRowsDelete(int ID, out string ErrorMessage);
        ChemicalInUse AutoGeneratedCode();
        Chemicals ChemicalNameData(int ChemicalId);
    }
}
