using CP.UETrack.Model.CLS;
using System.Collections.Generic;

namespace CP.UETrack.DAL.DataAccess.Contracts.CLS
{
    public interface ICorrectiveActionReportDAL
    {
        CorrectiveActionReportLovs Load();
        CorrectiveActionReport AutoGeneratedCode();
        List<CorrectiveActionReport> CARNoFetch(CorrectiveActionReport SearchObject);
        CorrectiveActionReport Save(CorrectiveActionReport block, out string ErrorMessage);
        CARHistoryDetails GetCARHistoryDetails(int Id);
        List<CARAttachment> AttachmentSave(CorrectiveActionReport block, out string ErrorMessage);
        CP.UETrack.Model.GridFilterResult GetAll(CP.UETrack.Model.SortPaginateFilter pageFilter);
        CorrectiveActionReport Get(int Id);
    }
}
