using CP.UETrack.Model;
using CP.UETrack.Model.CLS;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CP.UETrack.DAL.DataAccess.Contracts.CLS
{
   public interface IDailyCleaningActivityDAL
    {
        DailyCleaningActivityDropDown Load();
        DailyCleaningActivity Save(DailyCleaningActivity userRole, out string ErrorMessage);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        DailyCleaningActivity Get(int Id);
        DailyCleaningActivity AutoGeneratedCode();
        DailyCleaningActivity DocFetch(DailyCleaningActivity dailyCleaning);
    }
}
