using System;
using CP.UETrack.Model.CLS;
using CP.UETrack.Model;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CP.UETrack.DAL.DataAccess.Contracts.CLS
{
    public interface IPeriodicWorkRecordDAL
    {
        PeriodidcWorkRecordDropdown Load();
        PeriodicWorkRecord Save(PeriodicWorkRecord block, out string ErrorMessage);
        GridFilterResult GetAll(SortPaginateFilter pageFilter);
        PeriodicWorkRecord Get(int Id);
        PeriodicWorkRecord AutoGeneratedCode();
        PeriodicWorkRecord DocFetch(PeriodicWorkRecord periodicWork);
    }
}
