using CP.Framework.Common.ExceptionHandler.ExceptionWrappers;
using CP.Framework.Common.Logging;
using CP.UETrack.DAL.DataAccess.Contracts.CLS;
using CP.UETrack.Model.CLS;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using UETrack.DAL;
using CP.UETrack.DAL.DataAccess.Implementation;


namespace CP.UETrack.DAL.DataAccess.Implementations.CLS
{
    public class CorrectiveActionReportDAL : Contracts.CLS.ICorrectiveActionReportDAL
    {
        private readonly string _FileName = nameof(CorrectiveActionReportDAL);
        readonly UETrack.Model.UserDetailsModel _UserSession = new SessionHelper().UserSession();

        public CorrectiveActionReportLovs Load()
        {
            try
            {
                Log4NetLogger.LogEntry(_FileName, nameof(Load), Level.Info.ToString());

                var ds = new DataSet();
                var dbAccessDAL = new DBAccessDAL();
                CorrectiveActionReportLovs correctiveActionReportLovs = new CorrectiveActionReportLovs();
                using (SqlConnection con = new SqlConnection(dbAccessDAL.ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand())
                    {
                        var da = new SqlDataAdapter();
                        cmd.Connection = con;
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.CommandText = "Sp_CLS_CAR_DropDown";
                        cmd.Parameters.Clear();
                        cmd.Parameters.AddWithValue("@pScreenName", "CorrectiveActionReport");
                        da.SelectCommand = cmd;
                        da.Fill(ds);
                        if (ds.Tables[0] != null)
                        {
                            correctiveActionReportLovs.CARPriorityValues = dbAccessDAL.GetLovRecords(ds.Tables[0]);
                        }
                        if (ds.Tables[1] != null)
                        {
                            correctiveActionReportLovs.CARStatusValues = dbAccessDAL.GetLovRecords(ds.Tables[1]);
                        }
                        if (ds.Tables[2] != null)
                        {
                            correctiveActionReportLovs.CARResponsibilityValues = dbAccessDAL.GetLovRecords(ds.Tables[2]);
                        }
                        if (ds.Tables[3] != null)
                        {
                            correctiveActionReportLovs.FileTypeLovs = dbAccessDAL.GetLovRecords(ds.Tables[3]);
                        }
                        if (ds.Tables[4] != null)
                        {
                            correctiveActionReportLovs.IndicatorValues = dbAccessDAL.GetLovRecords(ds.Tables[4]);
                        }

                    }
                }
                Log4NetLogger.LogExit(_FileName, nameof(Load), Level.Info.ToString());
                return correctiveActionReportLovs;
            }
            catch (DALException dalex)
            {
                throw new DALException(dalex);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public CorrectiveActionReport AutoGeneratedCode()
        {
            try
            {
                Log4NetLogger.LogEntry(_FileName, nameof(AutoGeneratedCode), Level.Info.ToString());
                CorrectiveActionReport correctiveActionReport = new CorrectiveActionReport();

                var ds = new DataSet();

                var dbAccessDAL = new DBAccessDAL();
                using (SqlConnection con = new SqlConnection(dbAccessDAL.ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand())
                    {
                        cmd.Connection = con;
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.CommandText = "Sp_CLS_CARAutoGenaratedCode";

                        var da = new SqlDataAdapter();
                        da.SelectCommand = cmd;
                        da.Fill(ds);
                    }
                }

                if (ds.Tables.Count != 0)
                {
                    correctiveActionReport = (from n in ds.Tables[0].AsEnumerable()
                                              select new CorrectiveActionReport
                                              {
                                                  CARNo = Convert.ToString(n["CARNo"])
                                              }).FirstOrDefault();
                }
                if (ds.Tables[1].Rows.Count > 0)
                {
                    List<CorrectiveActionReport> CorrectiveActionReportList = new List<CorrectiveActionReport>();
                    foreach (DataRow dr in ds.Tables[1].Rows)
                    {
                        CorrectiveActionReport Corrective = new CorrectiveActionReport();
                        Corrective.Indicator = dr["IndicatorNo"].ToString();
                        CorrectiveActionReportList.Add(Corrective);
                    }
                    correctiveActionReport.AutoDisplay = CorrectiveActionReportList;
                }



                Log4NetLogger.LogExit(_FileName, nameof(AutoGeneratedCode), Level.Info.ToString());
                return correctiveActionReport;
            }
            catch (DALException dalex)
            {
                throw new DALException(dalex);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public List<CorrectiveActionReport> CARNoFetch(CorrectiveActionReport searchObject)
        {
            try
            {
                Log4NetLogger.LogEntry(_FileName, nameof(CARNoFetch), Level.Info.ToString());
                List<CorrectiveActionReport> result = null;
                var pageIndex = searchObject.PageIndex;
                var pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["FetchPopupPageSize"]);
                var dbAccessDAL = new DBAccessDAL();
                var obj = new CorrectiveActionReport();
                var DataSetparameters = new Dictionary<string, DataTable>();
                var parameters = new Dictionary<string, string>();
                parameters.Add("@CARNo", searchObject.CARNo ?? "");
                parameters.Add("@pPageIndex", Convert.ToString(pageIndex));
                parameters.Add("@pPageSize", Convert.ToString(pageSize));
                parameters.Add("@pFacilityId", _UserSession.FacilityId.ToString());
                DataTable dt = dbAccessDAL.GetDataTable("Sp_CLS_CARNoFetch", parameters, DataSetparameters);
                if (dt != null && dt.Rows.Count > 0)
                {
                    var totalRecords = Convert.ToInt32(dt.Rows[0]["TotalRecords"]);
                    var firstRecord = (pageIndex - 1) * pageSize + 1;
                    var lastRecord = (pageIndex - 1) * pageSize + dt.Rows.Count;
                    var lastPageIndex = totalRecords % pageSize == 0 ? totalRecords / pageSize : (totalRecords / pageSize) + 1;

                    result = (from n in dt.AsEnumerable()
                              select new CorrectiveActionReport
                              {
                                  CARId = Convert.ToInt32(n["CARId"].ToString()),
                                  CARNo = Convert.ToString(n["CARNo"]),
                                  TotalRecords = totalRecords,
                                  FirstRecord = firstRecord,
                                  LastRecord = lastRecord,
                                  LastPageIndex = lastPageIndex
                              }).ToList();
                }
                Log4NetLogger.LogExit(_FileName, nameof(CARNoFetch), Level.Info.ToString());
                return result;
            }
            catch (DALException dalex)
            {
                throw new DALException(dalex);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public CorrectiveActionReport Save(CorrectiveActionReport model, out string ErrorMessage)
        {
            try
            {
                Log4NetLogger.LogEntry(_FileName, nameof(Save), Level.Info.ToString());
                ErrorMessage = string.Empty;
                var spName = string.Empty;
                var ds = new DataSet();

                var dbAccessDAL = new DBAccessDAL();
                using (SqlConnection con = new SqlConnection(dbAccessDAL.ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand())
                    {
                        cmd.Connection = con;
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.CommandText = "Sp_CLS_CorrectiveActionReport";

                        cmd.Parameters.AddWithValue("@CARId", model.CARId);
                        cmd.Parameters.AddWithValue("@Customerid", model.CustomerId);
                        cmd.Parameters.AddWithValue("@Facilityid", model.FacilityId);
                        cmd.Parameters.AddWithValue("@CARGeneration", model.CARGeneration);
                        cmd.Parameters.AddWithValue("@CARNo", model.CARNo);
                        cmd.Parameters.AddWithValue("@Indicator", model.Indicator);
                        cmd.Parameters.AddWithValue("@CARDate", model.CARDate);
                        cmd.Parameters.AddWithValue("@CARPeriodFrom", model.CARPeriodFrom);
                        cmd.Parameters.AddWithValue("@CARPeriodTo", model.CARPeriodTo);
                        cmd.Parameters.AddWithValue("@FollowUpCAR", model.FollowUpCAR);
                        cmd.Parameters.AddWithValue("@Assignee", model.Assignee);
                        cmd.Parameters.AddWithValue("@ProblemStatement", model.ProblemStatement);
                        cmd.Parameters.AddWithValue("@RootCause", model.RootCause);
                        cmd.Parameters.AddWithValue("@Solution", model.Solution);
                        cmd.Parameters.AddWithValue("@Priority", model.Priority);
                        cmd.Parameters.AddWithValue("@Status", model.Status);
                        cmd.Parameters.AddWithValue("@Issuer", model.Issuer);
                        cmd.Parameters.AddWithValue("@CARTargetDate", model.CARTargetDate);
                        cmd.Parameters.AddWithValue("@VerifiedDate", model.VerifiedDate);
                        cmd.Parameters.AddWithValue("@VerifiedBy", model.VerifiedBy);
                        cmd.Parameters.AddWithValue("@Remarks", model.Remarks);

                        var da = new SqlDataAdapter();
                        da.SelectCommand = cmd;
                        da.Fill(ds);

                        if (ds.Tables.Count != 0)
                        {
                            cmd.Parameters.Clear();
                            model.CARId = Convert.ToInt32(ds.Tables[0].Rows[0]["CARId"]);
                            var ds1 = new DataSet();
                            cmd.CommandText = "Sp_CLS_CARActivityTxn";

                            foreach (var CAR in model.CARActivityList)
                            {
                                cmd.Parameters.Clear();
                                cmd.Parameters.AddWithValue("@CARActivityId", CAR.CARActivityId);
                                cmd.Parameters.AddWithValue("@Activity", CAR.Activity);
                                cmd.Parameters.AddWithValue("@StartDate", CAR.StartDate);
                                cmd.Parameters.AddWithValue("@TargetDate", CAR.TargetDate);
                                cmd.Parameters.AddWithValue("@ActualCompletionDate", CAR.ActualCompletionDate);
                                cmd.Parameters.AddWithValue("@Responsibility", CAR.Responsibility);
                                cmd.Parameters.AddWithValue("@ResponsiblePerson", CAR.ResponsiblePerson);
                                cmd.Parameters.AddWithValue("@CARId", model.CARId);
                                cmd.Parameters.AddWithValue("@isDeleted", CAR.isDeleted);

                                da.SelectCommand = cmd;
                                da.Fill(ds1);
                                
                            }
                            model = Get(model.CARId);
                        }
                    }
                }
                model = Get(model.CARId);

                Log4NetLogger.LogExit(_FileName, nameof(Save), Level.Info.ToString());
                return model;
            }
            catch (DALException dalex)
            {
                throw new DALException(dalex);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public CARHistoryDetails GetCARHistoryDetails(int Id)
        {
            try
            {
                Log4NetLogger.LogEntry(_FileName, nameof(GetCARHistoryDetails), Level.Info.ToString());
                var CARHistoryDetails = new CARHistoryDetails();

                var ds = new DataSet();
                var dbAccessDAL = new DBAccessDAL();
                using (SqlConnection con = new SqlConnection(dbAccessDAL.ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand())
                    {
                        cmd.Connection = con;
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.CommandText = "Sp_CLS_CAR_GetHistoryDetails";
                        cmd.Parameters.AddWithValue("@pCARId", Id);

                        var da = new SqlDataAdapter();
                        da.SelectCommand = cmd;
                        da.Fill(ds);
                    }
                }
                if (ds.Tables.Count != 0 && ds.Tables[0].Rows.Count > 0)
                {
                    DataRow dr = ds.Tables[0].Rows[0];
                    CARHistoryDetails.StatusValue = dr["Status"].ToString();
                    CARHistoryDetails.RootCause = dr["RootCause"].ToString();
                    CARHistoryDetails.Solution = dr["Solution"].ToString();
                    CARHistoryDetails.Remarks = dr["Remarks"].ToString();
                }

                Log4NetLogger.LogExit(_FileName, nameof(GetCARHistoryDetails), Level.Info.ToString());
                return CARHistoryDetails;
            }
            catch (DALException dalex)
            {
                throw new DALException(dalex);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public List<CARAttachment> AttachmentSave(CorrectiveActionReport model, out string ErrorMessage)
        {
            try
            {
                Log4NetLogger.LogEntry(_FileName, nameof(AttachmentSave), Level.Info.ToString());
                ErrorMessage = string.Empty;
                var spName = string.Empty;

                var ds = new DataSet();
                var dbAccessDAL = new DBAccessDAL();

                List<CARAttachment> _lstCARAttachments = new List<CARAttachment>();

                using (SqlConnection con = new SqlConnection(dbAccessDAL.ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand())
                    {
                        cmd.Connection = con;
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.CommandText = "SP_CLS_CARAttachment";

                        foreach (var att in model.CARAttachmentList)
                        {
                            cmd.Parameters.AddWithValue("@AttachmentId", att.AttachmentId);
                            cmd.Parameters.AddWithValue("@CARId", model.CARId);
                            cmd.Parameters.AddWithValue("@FileType", att.FileType);
                            cmd.Parameters.AddWithValue("@FileName", att.FileName);
                            cmd.Parameters.AddWithValue("@AttachmentName", att.AttachmentName);
                            cmd.Parameters.AddWithValue("@FilePath", att.FilePath);
                            cmd.Parameters.AddWithValue("@isDeleted", att.isDeleted);

                            var da = new SqlDataAdapter();
                            da.SelectCommand = cmd;
                            da.Fill(ds);
                            cmd.Parameters.Clear();

                        }
                        //model = Get(model.CARId);
                    }
                }

                Log4NetLogger.LogExit(_FileName, nameof(AttachmentSave), Level.Info.ToString());
                return Get(model.CARId).CARAttachmentList;
            }
            catch (DALException dalex)
            {
                throw new DALException(dalex);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public CP.UETrack.Model.GridFilterResult GetAll(CP.UETrack.Model.SortPaginateFilter pageFilter)
        {
            try
            {
                Log4NetLogger.LogEntry(_FileName, nameof(GetAll), Level.Info.ToString());
                CP.UETrack.Model.GridFilterResult filterResult = null;

                var multipleOrderBy = pageFilter.SortColumn.Split(',');
                var strOrderBy = string.Empty;
                foreach (var order in multipleOrderBy)
                {
                    strOrderBy += order + " " + pageFilter.SortOrder + ",";
                }
                if (!string.IsNullOrEmpty(strOrderBy))
                {
                    strOrderBy = strOrderBy.TrimEnd(',');
                }

                strOrderBy = string.IsNullOrEmpty(strOrderBy) ? pageFilter.SortColumn + " " + pageFilter.SortOrder : strOrderBy;
                var strCondition = string.Empty;
                var QueryCondition = pageFilter.QueryWhereCondition;
                if (string.IsNullOrEmpty(QueryCondition))
                {
                    strCondition = "FacilityId = " + _UserSession.FacilityId.ToString();
                }
                else
                {
                    strCondition = QueryCondition + " AND FacilityId = " + _UserSession.FacilityId.ToString();
                }
                var ds = new DataSet();
                var dbAccessDAL = new DBAccessDAL();
                using (SqlConnection con = new SqlConnection(dbAccessDAL.ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand())
                    {
                        cmd.Connection = con;
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.CommandText = "sp_CLS_CorrectiveActionReport_GetAll";

                        cmd.Parameters.AddWithValue("@PageIndex", pageFilter.PageIndex);
                        cmd.Parameters.AddWithValue("@PageSize", pageFilter.PageSize);
                        cmd.Parameters.AddWithValue("@StrCondition", strCondition);
                        cmd.Parameters.AddWithValue("@StrSorting", strOrderBy);

                        var da = new SqlDataAdapter();
                        da.SelectCommand = cmd;
                        da.Fill(ds);
                    }
                }
                if (ds.Tables.Count != 0 && ds.Tables[0].Rows.Count > 0)
                {
                    var totalRecords = Convert.ToInt32(ds.Tables[0].Rows[0]["TotalRecords"]);
                    var totalPages = (int)Math.Ceiling((float)totalRecords / (float)pageFilter.Rows);

                    var commonDAL = new CommonDAL();
                    var currentPageList = commonDAL.ToDynamicList(ds.Tables[0]);
                    filterResult = new CP.UETrack.Model.GridFilterResult
                    {
                        TotalRecords = totalRecords,
                        TotalPages = totalPages,
                        RecordsList = currentPageList,
                        CurrentPage = pageFilter.Page
                    };
                }
                Log4NetLogger.LogExit(_FileName, nameof(GetAll), Level.Info.ToString());
                //return Blocks;
                return filterResult;
            }
            catch (DALException dalex)
            {
                throw new DALException(dalex);
            }
            catch (Exception)
            {
                throw;
            }
        }

        public CorrectiveActionReport Get(int Id)
        {
            try
            {
                Log4NetLogger.LogEntry(_FileName, nameof(Get), Level.Info.ToString());

                var ds = new DataSet();
                var dbAccessDAL = new DBAccessDAL();
                using (SqlConnection con = new SqlConnection(dbAccessDAL.ConnectionString))
                {
                    using (SqlCommand cmd = new SqlCommand())
                    {
                        cmd.Connection = con;
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.CommandText = "Sp_CLS_CorrectiveActionReport_Get";
                        cmd.Parameters.AddWithValue("@CARId", Id);
                        var da = new SqlDataAdapter();
                        da.SelectCommand = cmd;
                        da.Fill(ds);
                    }
                }

                CorrectiveActionReport _correctiveActionReport = new CorrectiveActionReport();

                if (ds.Tables[0].Rows.Count > 0)
                {
                    DataRow dr = ds.Tables[0].Rows[0];

                    _correctiveActionReport.CARId = Convert.ToInt32(dr["CARId"]);
                    _correctiveActionReport.CARGeneration = dr["CARGeneration"].ToString();
                    _correctiveActionReport.CARNo = dr["CARNo"].ToString();
                    _correctiveActionReport.Indicator = dr["Indicator"].ToString();
                    if (dr["CARDate"] != System.DBNull.Value)
                        _correctiveActionReport.CARDate = Convert.ToDateTime(dr["CARDate"].ToString());

                    if (dr["CARPeriodFrom"] != System.DBNull.Value)
                        _correctiveActionReport.CARPeriodFrom = Convert.ToDateTime(dr["CARPeriodFrom"]);
                    if (dr["CARPeriodTo"] != System.DBNull.Value)
                        _correctiveActionReport.CARPeriodTo = Convert.ToDateTime(dr["CARPeriodTo"]);
                    _correctiveActionReport.FollowUpCAR = dr["FollowUpCAR"].ToString();
                    _correctiveActionReport.Assignee = dr["Assignee"].ToString();
                    _correctiveActionReport.ProblemStatement = dr["ProblemStatement"].ToString();

                    _correctiveActionReport.RootCause = dr["RootCause"].ToString();
                    _correctiveActionReport.Solution = dr["Solution"].ToString();
                    _correctiveActionReport.Priority = dr["Priority"].ToString();
                    _correctiveActionReport.Status = dr["Status"].ToString();
                    _correctiveActionReport.Issuer = dr["Issuer"].ToString();
                    if (dr["CARTargetDate"] != System.DBNull.Value)
                        _correctiveActionReport.CARTargetDate = Convert.ToDateTime(dr["CARTargetDate"]);
                    if (dr["VerifiedDate"] != System.DBNull.Value)
                        _correctiveActionReport.VerifiedDate = Convert.ToDateTime(dr["VerifiedDate"]);
                    _correctiveActionReport.VerifiedBy = dr["VerifiedBy"].ToString();
                    _correctiveActionReport.Remarks = dr["Remarks"].ToString();
                  
                }

                if (ds.Tables[1].Rows.Count > 0)
                {
                    List<CARActivity> _CarActivityList = new List<CARActivity>();

                    foreach (DataRow dr in ds.Tables[1].Rows)
                    {
                        CARActivity Auto = new CARActivity();
                        Auto.CARActivityId = Convert.ToInt32(dr["CARActivityId"]);
                        Auto.Activity = dr["Activity"].ToString();
                        Auto.StartDate = Convert.ToDateTime(dr["StartDate"]);
                        if (dr["TargetDate"] != System.DBNull.Value)
                            Auto.TargetDate = Convert.ToDateTime(dr["TargetDate"]);
                        if (dr["ActualCompletionDate"] != System.DBNull.Value)
                            Auto.ActualCompletionDate = Convert.ToDateTime(dr["ActualCompletionDate"]);
                        Auto.Responsibility = dr["Responsibility"].ToString();
                        Auto.ResponsiblePerson = dr["ResponsiblePerson"].ToString();

                        _CarActivityList.Add(Auto);
                    }
                    _correctiveActionReport.CARActivityList = _CarActivityList;
                }

                if (ds.Tables[2].Rows.Count > 0)
                {
                    List<CARAttachment> _carAttachmentList = new List<CARAttachment>();

                    foreach (DataRow dr in ds.Tables[2].Rows)
                    {
                        CARAttachment obj = new CARAttachment();

                        obj.AttachmentId = Convert.ToInt32(dr["AttachmentId"]);
                        obj.FileType = dr["FileType"].ToString();
                        obj.FileName = dr["FileName"].ToString();
                        obj.AttachmentName = dr["AttachmentName"].ToString();
                        obj.FilePath = dr["FilePath"].ToString();
                        _carAttachmentList.Add(obj);

                    }
                    _correctiveActionReport.CARAttachmentList = _carAttachmentList;
                }
                               
                Log4NetLogger.LogExit(_FileName, nameof(Get), Level.Info.ToString());
                return _correctiveActionReport;
            }
            catch (DALException dalex)
            {
                throw new DALException(dalex);
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}
