namespace CP.UETrack.Model
{
    public class PPMLoadBalancing
    {
        public int Year { get; set; }
        public int TotalNoOfWorkOrders { get; set; }
        public double AverageNoOfWorkOrders { get; set; }
        public int Jan1 { get; set; }
        public int Jan2 { get; set; }
        public int Jan3 { get; set; }
        public int Jan4 { get; set; }
        public int Jan5 { get; set; }
        public int Feb1 { get; set; }
        public int Feb2 { get; set; }
        public int Feb3 { get; set; }
        public int Feb4 { get; set; }
        public int Feb5 { get; set; }
        public int Mar1 { get; set; }
        public int Mar2 { get; set; }
        public int Mar3 { get; set; }
        public int Mar4 { get; set; }
        public int Mar5 { get; set; }
        public int Apr1 { get; set; }
        public int Apr2 { get; set; }
        public int Apr3 { get; set; }
        public int Apr4 { get; set; }
        public int Apr5 { get; set; }
        public int May1 { get; set; }
        public int May2 { get; set; }
        public int May3 { get; set; }
        public int May4 { get; set; }
        public int May5 { get; set; }
        public int Jun1 { get; set; }
        public int Jun2 { get; set; }
        public int Jun3 { get; set; }
        public int Jun4 { get; set; }
        public int Jun5 { get; set; }
        public int Jul1 { get; set; }
        public int Jul2 { get; set; }
        public int Jul3 { get; set; }
        public int Jul4 { get; set; }
        public int Jul5 { get; set; }
        public int Aug1 { get; set; }
        public int Aug2 { get; set; }
        public int Aug3 { get; set; }
        public int Aug4 { get; set; }
        public int Aug5 { get; set; }
        public int Sep1 { get; set; }
        public int Sep2 { get; set; }
        public int Sep3 { get; set; }
        public int Sep4 { get; set; }
        public int Sep5 { get; set; }
        public int Oct1 { get; set; }
        public int Oct2 { get; set; }
        public int Oct3 { get; set; }
        public int Oct4 { get; set; }
        public int Oct5 { get; set; }
        public int Nov1 { get; set; }
        public int Nov2 { get; set; }
        public int Nov3 { get; set; }
        public int Nov4 { get; set; }
        public int Nov5 { get; set; }
        public int Dec1 { get; set; }
        public int Dec2 { get; set; }
        public int Dec3 { get; set; }
        public int Dec4 { get; set; }
        public int Dec5 { get; set; }
        public int Total1 { get; set; }
        public int Total2 { get; set; }
        public int Total3 { get; set; }
        public int Total4 { get; set; }
        public int Total5 { get; set; }
        public int Total6 { get; set; }
        public int Total7 { get; set; }
        public int Total8 { get; set; }
        public int Total9 { get; set; }
        public int Total10 { get; set; }
        public int Total11 { get; set; }
        public int Total12 { get; set; }
    }
}