//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP.UETrack.TranslationManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CP.UETrack.TranslationManager.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added for the entered date.
        /// </summary>
        public static string AAaddedfortheentereddate {
            get {
                return ResourceManager.GetString("AAaddedfortheentereddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already added for the selected {1}.
        /// </summary>
        public static string AAAllocationBB {
            get {
                return ResourceManager.GetString("AAAllocationBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered {0} is already added/exist.
        /// </summary>
        public static string AAAlreadyAdded {
            get {
                return ResourceManager.GetString("AAAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} already exists. Please try another {0}..
        /// </summary>
        public static string AAAlreadyExist {
            get {
                return ResourceManager.GetString("AAAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exist for this {1}..
        /// </summary>
        public static string AAAlreadyExistForSelectedBB {
            get {
                return ResourceManager.GetString("AAAlreadyExistForSelectedBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists.
        /// </summary>
        public static string AAAlreadyExisting {
            get {
                return ResourceManager.GetString("AAAlreadyExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cannot be deleted as it is referred in another record!.
        /// </summary>
        public static string AAalreadyinuseandcannotbedeletedoredited {
            get {
                return ResourceManager.GetString("AAalreadyinuseandcannotbedeletedoredited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered {0} already mapped to another {1}.
        /// </summary>
        public static string AAAlreadyMapped {
            get {
                return ResourceManager.GetString("AAAlreadyMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already mapped to a different {1}.
        /// </summary>
        public static string AAalreadymappedtoadifferentBB {
            get {
                return ResourceManager.GetString("AAalreadymappedtoadifferentBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1},{2} combination already exist..
        /// </summary>
        public static string AABBCCCombinationExist {
            get {
                return ResourceManager.GetString("AABBCCCombinationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Combination of {0} ,{1},{2},{3},{4} already exist..
        /// </summary>
        public static string AABBCCDDEECombination {
            get {
                return ResourceManager.GetString("AABBCCDDEECombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0},{1} and {2} combination is already exists.
        /// </summary>
        public static string AABBCCExists {
            get {
                return ResourceManager.GetString("AABBCCExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} and {1} combination already exists.
        /// </summary>
        public static string AABBExists {
            get {
                return ResourceManager.GetString("AABBExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string AABBIsRequired {
            get {
                return ResourceManager.GetString("AABBIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        public static string AABetweenBBAndCC {
            get {
                return ResourceManager.GetString("AABetweenBBAndCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} cannot be less than {1}..
        /// </summary>
        public static string AACannotBeLessThanBB {
            get {
                return ResourceManager.GetString("AACannotBeLessThanBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string AAChangeCode {
            get {
                return ResourceManager.GetString("AAChangeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than previous {1}..
        /// </summary>
        public static string AAChangeVersion {
            get {
                return ResourceManager.GetString("AAChangeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Combination of {0} already exist..
        /// </summary>
        public static string AACombination {
            get {
                return ResourceManager.GetString("AACombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} is already exist. Please try another Date..
        /// </summary>
        public static string AAdateAlreadyExists {
            get {
                return ResourceManager.GetString("AAdateAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is Invalid date format. Enter in correct format (DD-MM-YYYY).
        /// </summary>
        public static string AADateInValid {
            get {
                return ResourceManager.GetString("AADateInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be a future date..
        /// </summary>
        public static string AADateNotFuture {
            get {
                return ResourceManager.GetString("AADateNotFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Date cannot be future date in Status (Inactive).
        /// </summary>
        public static string AADateNotFutureInactiveStatus {
            get {
                return ResourceManager.GetString("AADateNotFutureInactiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be grater than previous {1}.
        /// </summary>
        public static string AAdatevalidationBB {
            get {
                return ResourceManager.GetString("AAdatevalidationBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry already exists for the {0}..
        /// </summary>
        public static string AAEntryExist {
            get {
                return ResourceManager.GetString("AAEntryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCRS already added for the selected {0} and {1}.
        /// </summary>
        public static string AAEntryExistAlready {
            get {
                return ResourceManager.GetString("AAEntryExistAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} data for the selected {1} and {2} already exist.
        /// </summary>
        public static string AAEntryExistForSelectedBBCC {
            get {
                return ResourceManager.GetString("AAEntryExistForSelectedBBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be equal to current date.
        /// </summary>
        public static string AAEqualToday {
            get {
                return ResourceManager.GetString("AAEqualToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}File not found..
        /// </summary>
        public static string AAFileNotFound {
            get {
                return ResourceManager.GetString("AAFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than or equal to current date.
        /// </summary>
        public static string AAGreaterEqualToday {
            get {
                return ResourceManager.GetString("AAGreaterEqualToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than {1} {2}..
        /// </summary>
        public static string AAGreaterThanBBCC {
            get {
                return ResourceManager.GetString("AAGreaterThanBBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than or equal to {1} and less than {2}..
        /// </summary>
        public static string AAGreaterThanBBLessThanCC {
            get {
                return ResourceManager.GetString("AAGreaterThanBBLessThanCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than {1} and  less than or equal to {2}.
        /// </summary>
        public static string AAgreaterThanBBlessthanequalCC {
            get {
                return ResourceManager.GetString("AAgreaterThanBBlessthanequalCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than Current Date.
        /// </summary>
        public static string AAGreaterThanCurrentDate {
            get {
                return ResourceManager.GetString("AAGreaterThanCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than or equal to {1} and  less than or equal to {2}.
        /// </summary>
        public static string AAgreaterThanEqualBBlessthanequalCC {
            get {
                return ResourceManager.GetString("AAgreaterThanEqualBBlessthanequalCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than One.
        /// </summary>
        public static string AAGreaterThanOne {
            get {
                return ResourceManager.GetString("AAGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than Today.
        /// </summary>
        public static string AAGreaterThanToday {
            get {
                return ResourceManager.GetString("AAGreaterThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than zero..
        /// </summary>
        public static string AAGreaterThanZero {
            get {
                return ResourceManager.GetString("AAGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than {1}..
        /// </summary>
        public static string AAGreaterThenBB {
            get {
                return ResourceManager.GetString("AAGreaterThenBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than selected {1} {2}..
        /// </summary>
        public static string AAGreaterThenBBCC {
            get {
                return ResourceManager.GetString("AAGreaterThenBBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Should Be GreaterThan or equal to {1} and  LessThan or equal to {2}.
        /// </summary>
        public static string AAGreaterThenBBlessthanCC {
            get {
                return ResourceManager.GetString("AAGreaterThenBBlessthanCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than or equal to {1}..
        /// </summary>
        public static string AAGreaterThenOrEqualBB {
            get {
                return ResourceManager.GetString("AAGreaterThenOrEqualBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Date should be greater than {0} ..
        /// </summary>
        public static string AAGreaterThenOrEqualBBBB {
            get {
                return ResourceManager.GetString("AAGreaterThenOrEqualBBBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is Not less then today.
        /// </summary>
        public static string AAGreaterThenOrEqualToday {
            get {
                return ResourceManager.GetString("AAGreaterThenOrEqualToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is greater then today..
        /// </summary>
        public static string AAGreaterThenToday {
            get {
                return ResourceManager.GetString("AAGreaterThenToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be change to Inactive status as it is referred in another screens..
        /// </summary>
        public static string AAInactive {
            get {
                return ResourceManager.GetString("AAInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record with same {0} already exist/added.
        /// </summary>
        public static string AAIsAlreadyExist {
            get {
                return ResourceManager.GetString("AAIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record with same {0} ,{1} and {2} already exist.
        /// </summary>
        public static string AAIsAlreadyExistForThreeFields {
            get {
                return ResourceManager.GetString("AAIsAlreadyExistForThreeFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record with same {0} and {1} already exist.
        /// </summary>
        public static string AAIsAlreadyExistTwoField {
            get {
                return ResourceManager.GetString("AAIsAlreadyExistTwoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cannot be deleted as it is referred in another record.
        /// </summary>
        public static string AAIsAlreadyUseDelete {
            get {
                return ResourceManager.GetString("AAIsAlreadyUseDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} already in use and cannot be edited.
        /// </summary>
        public static string AAIsAlreadyUseEdit {
            get {
                return ResourceManager.GetString("AAIsAlreadyUseEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is {0} for your hospital..
        /// </summary>
        public static string AAIscode {
            get {
                return ResourceManager.GetString("AAIscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} approval date expires..
        /// </summary>
        public static string AAIsDateExpire {
            get {
                return ResourceManager.GetString("AAIsDateExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} depend on another screen cannot delete..
        /// </summary>
        public static string AAIsDependancy {
            get {
                return ResourceManager.GetString("AAIsDependancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was Expired!.
        /// </summary>
        public static string AAIsExpired {
            get {
                return ResourceManager.GetString("AAIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no {0} for your hospital..
        /// </summary>
        public static string AAIsNocode {
            get {
                return ResourceManager.GetString("AAIsNocode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is already given for this day..
        /// </summary>
        public static string AAIsOneDayEntry {
            get {
                return ResourceManager.GetString("AAIsOneDayEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is already given for this day. In case of emergency {1} you can proceed on your order..
        /// </summary>
        public static string AAIsPerOrderBB {
            get {
                return ResourceManager.GetString("AAIsPerOrderBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Please try another code..
        /// </summary>
        public static string AAIsPrimaryCode {
            get {
                return ResourceManager.GetString("AAIsPrimaryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exist for this Location. Please try another Location..
        /// </summary>
        public static string AAIsPrimaryLocation {
            get {
                return ResourceManager.GetString("AAIsPrimaryLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exist. Please try another name..
        /// </summary>
        public static string AAIsPrimaryName {
            get {
                return ResourceManager.GetString("AAIsPrimaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string AAIsRequired {
            get {
                return ResourceManager.GetString("AAIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exist.Please try another Date.
        /// </summary>
        public static string AAIsUniqueDate {
            get {
                return ResourceManager.GetString("AAIsUniqueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid {0} is required..
        /// </summary>
        public static string AAIsValidRequired {
            get {
                return ResourceManager.GetString("AAIsValidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be latter than {1}..
        /// </summary>
        public static string AAlatterThenBB {
            get {
                return ResourceManager.GetString("AAlatterThenBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Length must be lesser than or equal to {1}..
        /// </summary>
        public static string AALengthBB {
            get {
                return ResourceManager.GetString("AALengthBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Length must be between {1} and {2}..
        /// </summary>
        public static string AALengthBBtoCC {
            get {
                return ResourceManager.GetString("AALengthBBtoCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be less than or equal to current date.
        /// </summary>
        public static string AALessEqualCurrentDate {
            get {
                return ResourceManager.GetString("AALessEqualCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be less than or equal to current date.
        /// </summary>
        public static string AALessEqualToday {
            get {
                return ResourceManager.GetString("AALessEqualToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be lesser than or equal to {1} and greater than  {2}..
        /// </summary>
        public static string AALesserThanOrEqualBBAndGraterThanCC {
            get {
                return ResourceManager.GetString("AALesserThanOrEqualBBAndGraterThanCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be lesser than  {1}..
        /// </summary>
        public static string AALesserThenBB {
            get {
                return ResourceManager.GetString("AALesserThenBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be lesser than or equal to {1}..
        /// </summary>
        public static string AALesserThenOrEqualBB {
            get {
                return ResourceManager.GetString("AALesserThenOrEqualBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be lesser than  {1}..
        /// </summary>
        public static string AALessThanBB {
            get {
                return ResourceManager.GetString("AALessThanBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be lesser than or equal to {1}..
        /// </summary>
        public static string AALessThenOrEqualBB {
            get {
                return ResourceManager.GetString("AALessThenOrEqualBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have atleast one record.
        /// </summary>
        public static string AAMustHaveRecord {
            get {
                return ResourceManager.GetString("AAMustHaveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not created.
        /// </summary>
        public static string AANotCreated {
            get {
                return ResourceManager.GetString("AANotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not created for current month..
        /// </summary>
        public static string AANotCreatedFroMonth {
            get {
                return ResourceManager.GetString("AANotCreatedFroMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be less than {1}..
        /// </summary>
        public static string AANotLessThenBB {
            get {
                return ResourceManager.GetString("AANotLessThenBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null if status is Inactive.
        /// </summary>
        public static string AANotNull {
            get {
                return ResourceManager.GetString("AANotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry already exists for the month.
        /// </summary>
        public static string AAPerMonthBB {
            get {
                return ResourceManager.GetString("AAPerMonthBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} record already added for the selected {1} , {2} &amp; {3} and {4}.
        /// </summary>
        public static string AARecordAlreadyAddedBBCCDDEE {
            get {
                return ResourceManager.GetString("AARecordAlreadyAddedBBCCDDEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} record already added for the selected {1} , {2} &amp; {3} and {4}.
        /// </summary>
        public static string AARecordAlreadyAddedBBCCDDEE1 {
            get {
                return ResourceManager.GetString("AARecordAlreadyAddedBBCCDDEE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} record already added for the selected {1} , {2} , {3} &amp; {4} and {5}.
        /// </summary>
        public static string AARecordAlreadyAddedBBCCDDEEFF {
            get {
                return ResourceManager.GetString("AARecordAlreadyAddedBBCCDDEEFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} records miss match .
        /// </summary>
        public static string AARecordMissmatch {
            get {
                return ResourceManager.GetString("AARecordMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} ({1}) already exists..
        /// </summary>
        public static string AASelectedCodeExisting {
            get {
                return ResourceManager.GetString("AASelectedCodeExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} ({1}) is invalid..
        /// </summary>
        public static string AASelectedCodeValidRequired {
            get {
                return ResourceManager.GetString("AASelectedCodeValidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than zero..
        /// </summary>
        public static string AAShouldBeGraterThenZero {
            get {
                return ResourceManager.GetString("AAShouldBeGraterThenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Should Be GreaterThan {1} and {0} Should Be LessThan {2}.
        /// </summary>
        public static string AAShouldBeGreaterThanBBandAAShouldBeLessThanCC {
            get {
                return ResourceManager.GetString("AAShouldBeGreaterThanBBandAAShouldBeLessThanCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective date for the latest {0} should be greater than previous {0} End date..
        /// </summary>
        public static string AAShouldBeGreaterThanPreviousBB {
            get {
                return ResourceManager.GetString("AAShouldBeGreaterThanPreviousBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be in {1}..
        /// </summary>
        public static string AAShouldBeInBB {
            get {
                return ResourceManager.GetString("AAShouldBeInBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be done only for past month transaction..
        /// </summary>
        public static string AAShouldBePastMonth {
            get {
                return ResourceManager.GetString("AAShouldBePastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be within selected {1} and {2}..
        /// </summary>
        public static string AAshouldbewithinselectedBBandCC {
            get {
                return ResourceManager.GetString("AAshouldbewithinselectedBBandCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value should be less than hundred..
        /// </summary>
        public static string AAShouldLessThanHundred {
            get {
                return ResourceManager.GetString("AAShouldLessThanHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be in {1}..
        /// </summary>
        public static string AAShouldNotBeInBB {
            get {
                return ResourceManager.GetString("AAShouldNotBeInBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Deduction closed for this  {0} date..
        /// </summary>
        public static string AAShouldNotBePastMonth {
            get {
                return ResourceManager.GetString("AAShouldNotBePastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} should not be same..
        /// </summary>
        public static string AAShouldNotBeSame {
            get {
                return ResourceManager.GetString("AAShouldNotBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Transaction is closed for current month..
        /// </summary>
        public static string AATransactionClosed {
            get {
                return ResourceManager.GetString("AATransactionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction cannot be added for the current day..
        /// </summary>
        public static string AATransactionLaps {
            get {
                return ResourceManager.GetString("AATransactionLaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be unique for {1}..
        /// </summary>
        public static string AAUniqueBB {
            get {
                return ResourceManager.GetString("AAUniqueBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} should be within the selected year.
        /// </summary>
        public static string AAWithinBB {
            get {
                return ResourceManager.GetString("AAWithinBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be with in Planned month and equal to or greater than current date..
        /// </summary>
        public static string AAWithInPlannedMonth {
            get {
                return ResourceManager.GetString("AAWithInPlannedMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be with in Planned year and greater than current date..
        /// </summary>
        public static string AAWithInPlannedYear {
            get {
                return ResourceManager.GetString("AAWithInPlannedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already used.
        /// </summary>
        public static string ABrandAlreadyused {
            get {
                return ResourceManager.GetString("ABrandAlreadyused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} user only allow to access BER2.
        /// </summary>
        public static string AccessMessage {
            get {
                return ResourceManager.GetString("AccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Activity and Sub activity already added/exist.
        /// </summary>
        public static string ActivityUnique {
            get {
                return ResourceManager.GetString("ActivityUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Already Added for the Same Effective Date..
        /// </summary>
        public static string AlreadyAddedSameDate {
            get {
                return ResourceManager.GetString("AlreadyAddedSameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Already Exist.
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} already exist in BasePermission. Please try another {0}..
        /// </summary>
        public static string AlreadyExistinBasePermission {
            get {
                return ResourceManager.GetString("AlreadyExistinBasePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be added for current or future period(month).
        /// </summary>
        public static string AlreadyExistMonth {
            get {
                return ResourceManager.GetString("AlreadyExistMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  and {1} is already exists Please try another.
        /// </summary>
        public static string AlreadyExistMonthAndYear {
            get {
                return ResourceManager.GetString("AlreadyExistMonthAndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already added for the selected period.
        /// </summary>
        public static string AlreadyExistPeriod {
            get {
                return ResourceManager.GetString("AlreadyExistPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Is Already Mapped..
        /// </summary>
        public static string AlreadyMapped {
            get {
                return ResourceManager.GetString("AlreadyMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already in use, cannot be deleted.
        /// </summary>
        public static string AlreadyUsed {
            get {
                return ResourceManager.GetString("AlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already in use, cannot be InActive.
        /// </summary>
        public static string AlreadyUsedInActive {
            get {
                return ResourceManager.GetString("AlreadyUsedInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least select one {0} check box to proceed with Approved button.
        /// </summary>
        public static string ApprovedFilter {
            get {
                return ResourceManager.GetString("ApprovedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}should be Equal to {1}..
        /// </summary>
        public static string ASISEqual {
            get {
                return ResourceManager.GetString("ASISEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Asset No..
        /// </summary>
        public static string AssetNoDuplicate {
            get {
                return ResourceManager.GetString("AssetNoDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance already added for the selected Service {0} and Year &amp; Month {1} &amp; {2}..
        /// </summary>
        public static string AttendanceAlreadyAddedAABB {
            get {
                return ResourceManager.GetString("AttendanceAlreadyAddedAABB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only previous month record should be editable within 10th of current month..
        /// </summary>
        public static string AttendanceNotEditable {
            get {
                return ResourceManager.GetString("AttendanceNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washing details already added for the selected {0}, {1} ,{2} and {3}..
        /// </summary>
        public static string BagHolderAlreadyAddedAABBCCDD {
            get {
                return ResourceManager.GetString("BagHolderAlreadyAddedAABBCCDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type Code, Manufacturer, Make, Brand, Model and PPM Frequency combination already exist..
        /// </summary>
        public static string BEMSHEPPMCombinationExist {
            get {
                return ResourceManager.GetString("BEMSHEPPMCombinationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For previous month, Form A can be generated after {0}th of current month..
        /// </summary>
        public static string CannotAddRecord {
            get {
                return ResourceManager.GetString("CannotAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} having many child references, which cannot be deleted.
        /// </summary>
        public static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save the record in Central Clean Linen store Screen First..
        /// </summary>
        public static string Cclssavevalidation {
            get {
                return ResourceManager.GetString("Cclssavevalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid {0} is required..
        /// </summary>
        public static string CheckbyStaffname {
            get {
                return ResourceManager.GetString("CheckbyStaffname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the {0} in the mentioned screen(s) _ {1}.
        /// </summary>
        public static string CheckStatus {
            get {
                return ResourceManager.GetString("CheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered {0}  already added/exist.
        /// </summary>
        public static string CodeValidation {
            get {
                return ResourceManager.GetString("CodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This combination already exist.
        /// </summary>
        public static string CombinationExist {
            get {
                return ResourceManager.GetString("CombinationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cannot be changed once Company is InActive.
        /// </summary>
        public static string CompanyInActiveCheck {
            get {
                return ResourceManager.GetString("CompanyInActiveCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract not expired and cannot be deleted.
        /// </summary>
        public static string ContractExpiredValidation {
            get {
                return ResourceManager.GetString("ContractExpiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Supplier Name ..
        /// </summary>
        public static string ContractorDuplicate {
            get {
                return ResourceManager.GetString("ContractorDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be less or equal to Max cost and greater than or equal to  Min cost..
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSWR record already added for the selected {0}, {1}, {2} and {3}..
        /// </summary>
        public static string CSWRecordAlreadyAddedAABBCCDD {
            get {
                return ResourceManager.GetString("CSWRecordAlreadyAddedAABBCCDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already added for the selected {0} {1} {2} and {3}..
        /// </summary>
        public static string CWIRecordAlreadyAddedAABBCCDDEE {
            get {
                return ResourceManager.GetString("CWIRecordAlreadyAddedAABBCCDDEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWRS record already/exist for the selected date.
        /// </summary>
        public static string CWRSAlreadyExists {
            get {
                return ResourceManager.GetString("CWRSAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be greater than {1}..
        /// </summary>
        public static string DateNotGreaterThan {
            get {
                return ResourceManager.GetString("DateNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details already added for the selected date.
        /// </summary>
        public static string DateValidation {
            get {
                return ResourceManager.GetString("DateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not exceeds days in the selected month.
        /// </summary>
        public static string DaysInMonthExceedsErrorMsg {
            get {
                return ResourceManager.GetString("DaysInMonthExceedsErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedection transaction mapping not done for the selected {0} {1} and {2}..
        /// </summary>
        public static string DedectionNotDoneFortheSelectedAABBCC {
            get {
                return ResourceManager.GetString("DedectionNotDoneFortheSelectedAABBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Adjustment Completed for {0},{1} and {2}..
        /// </summary>
        public static string DeductionAdjustedAABBCC {
            get {
                return ResourceManager.GetString("DeductionAdjustedAABBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Generated for {0},{1} and {2}..
        /// </summary>
        public static string DeductionGeneratedAABBCC {
            get {
                return ResourceManager.GetString("DeductionGeneratedAABBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Transaction Mapping not generated for the selected {0} {1} and {2}..
        /// </summary>
        public static string DeductionMappingDetailsAABBCC {
            get {
                return ResourceManager.GetString("DeductionMappingDetailsAABBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Indicators should be mapped for the selected {0} {1} and {2}..
        /// </summary>
        public static string DeductionMappingIndicatorAABBCC {
            get {
                return ResourceManager.GetString("DeductionMappingIndicatorAABBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Not Generated for {0},{1} and {2}..
        /// </summary>
        public static string DeductionNotGeneratedAABBCC {
            get {
                return ResourceManager.GetString("DeductionNotGeneratedAABBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exist/added, cannot add record for the same year. Please edit..
        /// </summary>
        public static string DEDYearValidationMsg {
            get {
                return ResourceManager.GetString("DEDYearValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved/Reject Date should be greater than or equal to Document .
        /// </summary>
        public static string DefectDetailsDate {
            get {
                return ResourceManager.GetString("DefectDetailsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be deleted because this {0} is already in use !.
        /// </summary>
        public static string DeleteCheck {
            get {
                return ResourceManager.GetString("DeleteCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed!.
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string DirectMessage {
            get {
                return ResourceManager.GetString("DirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Not Allow Future Date.
        /// </summary>
        public static string DocumentDateValidation {
            get {
                return ResourceManager.GetString("DocumentDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Not Allow Past Date.
        /// </summary>
        public static string DueDateValidation {
            get {
                return ResourceManager.GetString("DueDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exist/added.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0} exist.
        /// </summary>
        public static string DuplicateAAExist {
            get {
                return ResourceManager.GetString("DuplicateAAExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exist for the selected {0} and {1} , cannot be added..
        /// </summary>
        public static string DuplicateCombination {
            get {
                return ResourceManager.GetString("DuplicateCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0}  already exist/added.
        /// </summary>
        public static string DuplicateErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records already inserted for selected service.
        /// </summary>
        public static string DuplicateInsert {
            get {
                return ResourceManager.GetString("DuplicateInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exists for same month.
        /// </summary>
        public static string DuplicateMonthExists {
            get {
                return ResourceManager.GetString("DuplicateMonthExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWRS record for the entered  {0} is already assigned to another DWRS record.
        /// </summary>
        public static string DWRSDATE {
            get {
                return ResourceManager.GetString("DWRSDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} should be greater than previous {0} ..
        /// </summary>
        public static string EffectiveDatePV {
            get {
                return ResourceManager.GetString("EffectiveDatePV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id Not Found For The User.
        /// </summary>
        public static string EmailIdNotFound {
            get {
                return ResourceManager.GetString("EmailIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be empty!.
        /// </summary>
        public static string EmptyMsg {
            get {
                return ResourceManager.GetString("EmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered {0} already added.
        /// </summary>
        public static string EnteredAAalreadyadded {
            get {
                return ResourceManager.GetString("EnteredAAalreadyadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving linen PAR requirement.
        /// </summary>
        public static string ErrorGettingPAR {
            get {
                return ResourceManager.GetString("ErrorGettingPAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Satisfaction survey already added for the selected User area, Quarter &amp; Year.
        /// </summary>
        public static string FeedbackAdded {
            get {
                return ResourceManager.GetString("FeedbackAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill  Mandatory fields across all pages in the grid prior to submission..
        /// </summary>
        public static string FemsDataErrorCompleteAll {
            get {
                return ResourceManager.GetString("FemsDataErrorCompleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Format..
        /// </summary>
        public static string FileFormat {
            get {
                return ResourceManager.GetString("FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This {0} already have data for this specified Month &amp; Year.
        /// </summary>
        public static string FilterProcess {
            get {
                return ResourceManager.GetString("FilterProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same {0} could not be repeated..
        /// </summary>
        public static string FilterTOP {
            get {
                return ResourceManager.GetString("FilterTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAC Data already  generated for selected {0},{1} and {2} combination, cannot be added..
        /// </summary>
        public static string FindEACDataGeneratedAABBCC {
            get {
                return ResourceManager.GetString("FindEACDataGeneratedAABBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction already  generated for selected {0},{1} and {2} combination, cannot be added..
        /// </summary>
        public static string FINDeductionGeneratedAABBCC {
            get {
                return ResourceManager.GetString("FINDeductionGeneratedAABBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with your request. Please contact system administrator..
        /// </summary>
        public static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than {1}..
        /// </summary>
        public static string GreaterThanIssueDate {
            get {
                return ResourceManager.GetString("GreaterThanIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Does Not Belongs To Access This Hospital.
        /// </summary>
        public static string HospitalIdHack {
            get {
                return ResourceManager.GetString("HospitalIdHack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create {0} before creating Company Site Office Profile..
        /// </summary>
        public static string HospitalProfileRequired {
            get {
                return ResourceManager.GetString("HospitalProfileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect {0} Enter valid {1}.
        /// </summary>
        public static string IncorrectAAEnterValidBB {
            get {
                return ResourceManager.GetString("IncorrectAAEnterValidBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is incorrect.
        /// </summary>
        public static string InCorrectPassword {
            get {
                return ResourceManager.GetString("InCorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Login Name Is Invalid.
        /// </summary>
        public static string InvalidLoginName {
            get {
                return ResourceManager.GetString("InvalidLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Invalid {0} .
        /// </summary>
        public static string InValidMessage {
            get {
                return ResourceManager.GetString("InValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Invalid Record..
        /// </summary>
        public static string InvalidRecord {
            get {
                return ResourceManager.GetString("InvalidRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} Selection.
        /// </summary>
        public static string InvalidSelection {
            get {
                return ResourceManager.GetString("InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} selected. New {1} should be greater than previous {2}.
        /// </summary>
        public static string IVAAGreaterThenBB {
            get {
                return ResourceManager.GetString("IVAAGreaterThenBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0} not allowed..
        /// </summary>
        public static string LinenDuplicate {
            get {
                return ResourceManager.GetString("LinenDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be lesser than or equal to {1} &amp; greater than or equal to {2}.
        /// </summary>
        public static string LinenRepairDate {
            get {
                return ResourceManager.GetString("LinenRepairDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Linen should be raised between 8.00 A.M to 8.00 P.M in any given day..
        /// </summary>
        public static string LinenTimeBetween {
            get {
                return ResourceManager.GetString("LinenTimeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location can not be inactivated till the associated transaction(s) are closed.
        /// </summary>
        public static string MakeInactive {
            get {
                return ResourceManager.GetString("MakeInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be made Inactive till associated transaction(s) are closed.
        /// </summary>
        public static string MakeInactiveForCompanyMst {
            get {
                return ResourceManager.GetString("MakeInactiveForCompanyMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manpower Norms already added for the selected Service {0}, Hospital Category {1}.
        /// </summary>
        public static string ManpowerAlreadyAddedAABBCCDD {
            get {
                return ResourceManager.GetString("ManpowerAlreadyAddedAABBCCDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} already mapped in {1} and Cannot be Delete!.
        /// </summary>
        public static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than 3 characters.
        /// </summary>
        public static string MinimumCode {
            get {
                return ResourceManager.GetString("MinimumCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than 2 characters.
        /// </summary>
        public static string MinimumCodeForAssetGroupDetails {
            get {
                return ResourceManager.GetString("MinimumCodeForAssetGroupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Behavior.
        /// </summary>
        public static string MiscellaneousBehavior {
            get {
                return ResourceManager.GetString("MiscellaneousBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1},{2} and {3} cannot be duplicate..
        /// </summary>
        public static string MMBMCombination {
            get {
                return ResourceManager.GetString("MMBMCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JKN email id not available, Please enter the data in MOH Staff Master Screen.
        /// </summary>
        public static string MOHStateEngineerEmail {
            get {
                return ResourceManager.GetString("MOHStateEngineerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions cannot be created for Closed months.
        /// </summary>
        public static string MonthClosedTrasaction {
            get {
                return ResourceManager.GetString("MonthClosedTrasaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Should be Next Year.
        /// </summary>
        public static string NextYear {
            get {
                return ResourceManager.GetString("NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Year record is not available for selected combination.
        /// </summary>
        public static string NoRecordsAvailable {
            get {
                return ResourceManager.GetString("NoRecordsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One {0} can have only two {1}.
        /// </summary>
        public static string OneAATwoBB {
            get {
                return ResourceManager.GetString("OneAATwoBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be Current and Past Date..
        /// </summary>
        public static string OnlyFutureDateValidation {
            get {
                return ResourceManager.GetString("OnlyFutureDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty Assessment already generated for selected {0},{1} and {2} combination, cannot be added..
        /// </summary>
        public static string PAGenerated {
            get {
                return ResourceManager.GetString("PAGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating already added for the selected parameter.
        /// </summary>
        public static string ParameterDuplicate {
            get {
                return ResourceManager.GetString("ParameterDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do not match.
        /// </summary>
        public static string PasswordMisMatch {
            get {
                return ResourceManager.GetString("PasswordMisMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty Generated Already for the selected Service {0} and Year &amp; Month {1} &amp; {2}..
        /// </summary>
        public static string PenaltyGeneratedAABBCC {
            get {
                return ResourceManager.GetString("PenaltyGeneratedAABBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Asset &amp; {0} combination already exist.Please change to proceed..
        /// </summary>
        public static string PlannerAssetTaskValidation {
            get {
                return ResourceManager.GetString("PlannerAssetTaskValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} not mached in this {1}.
        /// </summary>
        public static string ProperNo {
            get {
                return ResourceManager.GetString("ProperNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already modified..
        /// </summary>
        public static string RecordModified {
            get {
                return ResourceManager.GetString("RecordModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks required on Day {0} for Month {1}.
        /// </summary>
        public static string RemarksRequiredAABB {
            get {
                return ResourceManager.GetString("RemarksRequiredAABB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid {0} is required..
        /// </summary>
        public static string RepirbyStaffname {
            get {
                return ResourceManager.GetString("RepirbyStaffname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some {0 }are incorrect or have not been filled in. Please correct this to proceed..
        /// </summary>
        public static string RequiredTD {
            get {
                return ResourceManager.GetString("RequiredTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be Future Date..
        /// </summary>
        public static string ResponseDateTimeValidation {
            get {
                return ResourceManager.GetString("ResponseDateTimeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Route is already assigned and cannot be used!.
        /// </summary>
        public static string RouteAlreadyAssigned {
            get {
                return ResourceManager.GetString("RouteAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route code already assigned.
        /// </summary>
        public static string RouteCodeAlreadyAssigned {
            get {
                return ResourceManager.GetString("RouteCodeAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule already exists and cannot be generated.
        /// </summary>
        public static string ScheduleAlreadyExists {
            get {
                return ResourceManager.GetString("ScheduleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule not planned for the month.
        /// </summary>
        public static string ScheduleNotPlanned {
            get {
                return ResourceManager.GetString("ScheduleNotPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} already approved.
        /// </summary>
        public static string SelectedAAalreadyapprove {
            get {
                return ResourceManager.GetString("SelectedAAalreadyapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} already added/exist.
        /// </summary>
        public static string SelectedExist {
            get {
                return ResourceManager.GetString("SelectedExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Service Requests exists for the Asset for the selected Request type &apos;BER&apos;.
        /// </summary>
        public static string ServiceRequestValidateAssetNo {
            get {
                return ResourceManager.GetString("ServiceRequestValidateAssetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service work should not be edited when the status is Closed or Cancelled or Not Done &amp; Closed..
        /// </summary>
        public static string ServiceWorkLockedBasedOnStatus {
            get {
                return ResourceManager.GetString("ServiceWorkLockedBasedOnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be with in {1} and License End Date..
        /// </summary>
        public static string SP3RvendorApprovedDate {
            get {
                return ResourceManager.GetString("SP3RvendorApprovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User area master status in Other services is still active. It must be made inactive to proceed further / Active User locations are available. Make it inactive to proceed further.
        /// </summary>
        public static string StatusCheck {
            get {
                return ResourceManager.GetString("StatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Location is still active in other services. It must be made inactive to proceed further..
        /// </summary>
        public static string StatusCheckLocationCode {
            get {
                return ResourceManager.GetString("StatusCheckLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} should be Greater than Previous {0}..
        /// </summary>
        public static string STDStatusChanged {
            get {
                return ResourceManager.GetString("STDStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create {0} before creating Company site office profile..
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status and Test Result does not match..
        /// </summary>
        public static string TestResultCompliance {
            get {
                return ResourceManager.GetString("TestResultCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than/equal to {1}..
        /// </summary>
        public static string ToDateGreaterThanFromDate {
            get {
                return ResourceManager.GetString("ToDateGreaterThanFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater equal to {1}..
        /// </summary>
        public static string ToEqualFromDate {
            get {
                return ResourceManager.GetString("ToEqualFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater equal to {1}..
        /// </summary>
        public static string ToEqualThanFromDate {
            get {
                return ResourceManager.GetString("ToEqualThanFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be unique.
        /// </summary>
        public static string UniqueCodeMust {
            get {
                return ResourceManager.GetString("UniqueCodeMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be unique.
        /// </summary>
        public static string UniqueMust {
            get {
                return ResourceManager.GetString("UniqueMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Please upload valid data..
        /// </summary>
        public static string UploadEmptyRecord {
            get {
                return ResourceManager.GetString("UploadEmptyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date should be greater than Issue date.
        /// </summary>
        public static string ValidateDate {
            get {
                return ResourceManager.GetString("ValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than or equal to User Department Code {1}..
        /// </summary>
        public static string ValidateEffectiveFromDate {
            get {
                return ResourceManager.GetString("ValidateEffectiveFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is completed for the selected Date. Please select a Date greater than Adjustment Date..
        /// </summary>
        public static string ValidateStockDate {
            get {
                return ResourceManager.GetString("ValidateStockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} User can only save the record..
        /// </summary>
        public static string ValidateUser {
            get {
                return ResourceManager.GetString("ValidateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save the {0}.
        /// </summary>
        public static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid screen name..
        /// </summary>
        public static string VRCCheckScreen {
            get {
                return ResourceManager.GetString("VRCCheckScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Unloading completed for entered {0}.
        /// </summary>
        public static string WasteUnloadingcompletedforenteredAA {
            get {
                return ResourceManager.GetString("WasteUnloadingcompletedforenteredAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is greater than Consignment Note weight.
        /// </summary>
        public static string WasteUnloadingWeight {
            get {
                return ResourceManager.GetString("WasteUnloadingWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighing Scale No Should be Unique for all Waste Type.
        /// </summary>
        public static string WeighingScaleNoUnique {
            get {
                return ResourceManager.GetString("WeighingScaleNoUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Data Exists. Deletion not possible.
        /// </summary>
        public static string WorkGroupCode {
            get {
                return ResourceManager.GetString("WorkGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cannot be deleted as it is referred in another record.
        /// </summary>
        public static string WorkGroupCodeDeleteChildData {
            get {
                return ResourceManager.GetString("WorkGroupCodeDeleteChildData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cannot be deleted as it is referred in another record.
        /// </summary>
        public static string WorkGroupCodeDeleteChildRecord {
            get {
                return ResourceManager.GetString("WorkGroupCodeDeleteChildRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSEC Record Already added for the selected {0} and {1}..
        /// </summary>
        public static string WSECRecordAlreadyAddedAABB {
            get {
                return ResourceManager.GetString("WSECRecordAlreadyAddedAABB", resourceCulture);
            }
        }
    }
}
